source 'https://rubygems.org'

gem 'nokogiri', '~> 1.6.0'
gem 'json', '~> 1.8.0'
gem 'virtus', '~> 0.5.5'
gem 'data_mapper', '~> 1.2.0'

gem 'dm-postgres-adapter', '~> 1.2.0'
gem 'dm-sqlite-adapter', '~> 1.2.0'
gem 'rake', '~> 10.0.4'
gem 'savon', '~> 2.2.0'
gem 'factory_girl', '~> 4.2.0'
gem 'debugger'
gem 'sidekiq'
gem 'whenever'
gem 'rspec', '~> 2.13.0'
gem 'lumberjack'
gem 'require_all'
gem 'clockwork'
