require_relative 'parsers/base'
require_relative 'parsers/unimedia'
require_relative 'parsers/jurnal'
require_relative 'parsers/publika'
require_relative 'url-generators/unimedia'
require_relative 'fetchers/unimedia'
